---
- name: "Ubuntu Init Setup Playbook (Ubuntu Server 24.04 LTS)" 
  hosts: servers
  become_user: root
  tasks:

    - name: Set hostname
      hostname:
        name: "{{ host_name }}"
        use: systemd
      become: true
      when: ansible_hostname !=  host_name

    - name: Set timezone
      command: timedatectl set-timezone {{ ansible_timezone }}

    - name: Enable NTP synchronization
      command: timedatectl set-ntp true

    - name: Configure NTP servers
      command: timedatectl ntp-servers {{ ansible_ntp_intf }} {{ ansible_ntp_pool }}

    - name: Apt cache update
      apt:
        update_cache: yes
        cache_valid_time: 3600
    
    - name: Installed packages upgrade
      apt:
        upgrade: dist
      register: upgrade
      retries: 15
      delay: 5
      until: upgrade is success

    - name: Install preferred base packages
      apt:
        pkg:
          - nmap
          - vim
          - curl
          - git
          - figlet
          - htop
        state: latest

    - name: Disable cloud-init
      file:
        path: /etc/cloud/cloud-init.disabled
        state: touch
    
    - name: Disable motd-news
      lineinfile:
        path: /etc/default/motd-news
        regexp: '^ENABLED='
        line: ENABLED=0

    - name: Disable motd news file
      file:
        path: /etc/update-motd.d/50-motd-news
        mode: -x

    - name: Disable contract UA ESM status motd message
      file:
        path: /etc/update-motd.d/91-contract-ua-esm-status
        mode: -x

    - name: Disable motd release upgrade
      file: 
        path: /etc/update-motd.d/91-release-upgrade
        mode: -x

    - name: Disable motd release upgrade
      file: 
        path: /etc/update-motd.d/10-help-text
        mode: -x

    - name: Disable motd updates available
      file: 
        path: /etc/update-motd.d/90-updates-available
        mode: -x

    - name: Create issue.net file
      shell: hostname -s | figlet > /etc/issue.net
      args:
        executable: /bin/bash

    - name: Make issue.net output cleaner
      shell: echo "" >> /etc/issue.net
      args:
        executable: /bin/bash
    
    - name: Copy sshd config
      template:
        src: templates/99-n3s0-sshd.j2
        dest: /etc/ssh/sshd_config.d/99-n3s0.conf
    
    - name: Restart sshd service
      systemd_service:
        state: restarted
        daemon_reload: true
        name: sshd